  CREATE INDEX "LIBRA"."A_MCC_UPP_POSTCODE_LINE1_I" ON "LIBRA"."ADDRESSES" ("MCC_MCC_ID", UPPER(REPLACE("POSTCODE",' ','')), UPPER("LINE1"))
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
