  CREATE INDEX "APPREGISTER"."ALEFI_IDX" ON "APPREGISTER"."APP_LIST_ENTRY_FEE_ID" ("ALE_ALE_ID", "FEE_FEE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
