  CREATE INDEX "APPREGISTER"."AL_UPP_OC_IDX" ON "APPREGISTER"."APPLICATION_LISTS" (UPPER("OTHER_COURTHOUSE"))
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
