  CREATE INDEX "APPREGISTER"."AL_IDX" ON "APPREGISTER"."APPLICATION_LISTS" ("COURTHOUSE_CODE", "APPLICATION_LIST_DATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
