  CREATE INDEX "LIBRA"."LCM_ER_LCM_TYPE_DATE_I" ON "LIBRA"."LINK_COMMUNICATION_MEDIA" ("ER_ER_ID", "LCM_TYPE", "START_DATE", "END_DATE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
