  CREATE INDEX "LIBRA"."PSA_FAMILY_CASES_LOC_FK_I" ON "LIBRA"."PETTY_SESSIONAL_AREAS" ("FAMILY_CASES_LOC_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
