openapi: 3.0.4

info:
  title: Applications Register API
  description:
    REST API for managing Applications Lists, Application List Entries and getting important,
    reference data including Application Codes, Result Codes, Fees, Court Locations, Criminal Justice Areas
    and Standard Applicants.
  # We use @version@ here so Gradle can inject the project version at build time.
  # DO NOT change this to $version — Groovy template expansion conflicts with $ref
  # entries elsewhere in the file and will break the build.
  version: "@version@"

tags:
  - name: application-codes
    description:
      Application Codes are reference data, not managed in App Reg. They are required to provide a set repeatable data
      that can be used by Application List Entries, such as the title, wording or whether an application has an
      associated fee.
  - name: application-lists
    description:
      An Application List records the date, time and location at which one or more Applications is to be considered by a
      magistrate or delegated authority.
  - name: application-list-entries
    description:
      An Application List Entry records all details of an individual Application. This will always belong to an
      Application List.
  - name: application-list-entry-results
    description:
      An Application List Entry Result records the result of an individual Application. Each Application can have
      multiple child Results and Results cannot exist without a parent Application.
  - name: court-locations
    description:
      Court Locations are reference data, not managed in App Reg. They are a consolidation of both crown and magistrates
      courts where an application will be heard and resulted.
  - name: criminal-justice-areas
    description:
      Criminal Justice Areas are reference data, not managed in App Reg. They are officially recognized justice regions
      and used to classify records by jurisdiction.
  - name: result-codes
    description:
      Result codes are reference data, not managed in App Reg. They are required to provide a set of ways an Application
      List Entry can be resulted. e.g. Approved/Denied.
  - name: standard-applicants
    description:
      Standard Applicants are reference data, not managed in App Reg. They are pre-registered individuals stored in the
      system to streamline applications for recurring users, avoiding the need to manually re-enter their details each
      time they create applications.

paths:
  # APPLICATION CODES
  /application-codes:                                               { $ref: './paths/application-codes/application-codes.yaml' }
  /application-codes/{code}:                                        { $ref: './paths/application-codes/application-codes-by-code.yaml' }
  # APPLICATION LISTS
  /application-lists:                                               { $ref: './paths/application-lists/application-lists.yaml' }
  /application-lists/{listId}:                                      { $ref: './paths/application-lists/application-lists-by-id.yaml' }
  /application-lists/{listId}/print:                                { $ref: './paths/application-lists/printable-application-lists-by-id.yaml'}
  # APPLICATION LIST ENTRIES
  /application-list-entries:                                        { $ref: './paths/application-list-entries/entries.yaml' }
  /application-lists/{listId}/entries:                              { $ref: './paths/application-list-entries/application-list-entries.yaml' }
  /application-lists/{listId}/entries/{entryId}:                    { $ref: './paths/application-list-entries/application-list-entries-by-id.yaml' }
  # APPLICATION LIST ENTRY RESULTS
  /application-lists/{listId}/entries/{entryId}/results:            { $ref: './paths/application-list-entry-results/application-list-entry-results.yaml' }
  /application-lists/{listId}/entries/{entryId}/results/{resultId}: { $ref: './paths/application-list-entry-results/application-list-entry-results-by-id.yaml' }
  # COURT LOCATIONS
  /court-locations:                                                 { $ref: './paths/court-locations/court-locations.yaml' }
  /court-locations/{code}:                                          { $ref: './paths/court-locations/court-locations-by-code.yaml' }
  # CRIMINAL JUSTICE AREAS
  /criminal-justice-areas:                                          { $ref: './paths/criminal-justice-areas/criminal-justice-areas.yaml' }
  /criminal-justice-areas/{code}:                                   { $ref: './paths/criminal-justice-areas/criminal-justice-areas-by-code.yaml' }
  # RESULT CODES
  /result-codes:                                                    { $ref: './paths/result-codes/result-codes.yaml' }
  /result-codes/{code}:                                             { $ref: './paths/result-codes/result-codes-by-code.yaml' }
  # STANDARD APPLICANTS
  /standard-applicants:                                             { $ref: './paths/standard-applicants/standard-applicants.yaml' }
  /standard-applicants/{code}:                                      { $ref: './paths/standard-applicants/standard-applicants-by-code.yaml' }

components:
  schemas:
    # APPLICATION CODES
    application-code-get-summary-dto:   { $ref: './components/schemas/application-codes/application-code-get-summary-dto.yaml' }
    application-code-get-detail-dto:    { $ref: './components/schemas/application-codes/application-code-get-detail-dto.yaml' }
    application-code-page:              { $ref: './components/schemas/application-codes/application-code-page.yaml' }
    # APPLICATION LISTS
    application-list-get-detail-dto:    { $ref: './components/schemas/application-lists/application-list-get-detail-dto.yaml' }
    application-list-get-summary-dto:   { $ref: './components/schemas/application-lists/application-list-get-summary-dto.yaml' }
    application-list-create-dto:        { $ref: './components/schemas/application-lists/application-list-create-dto.yaml' }
    application-list-update-dto:        { $ref: './components/schemas/application-lists/application-list-update-dto.yaml' }
    application-list-page:              { $ref: './components/schemas/application-lists/application-list-page.yaml' }
    application-list-get-filter-dto:    { $ref: './components/schemas/application-lists/application-list-get-filter-dto.yaml' }
    application-list-get-print-dto:     { $ref: './components/schemas/application-lists/application-list-get-print-dto.yaml' }
    # APPLICATION LIST ENTRIES
    entry-get-print-dto:                { $ref: './components/schemas/application-list-entries/entry-get-print-dto.yaml'}
    entry-get-detail-dto:               { $ref: './components/schemas/application-list-entries/entry-get-detail-dto.yaml' }
    entry-create-dto:                   { $ref: './components/schemas/application-list-entries/entry-create-dto.yaml' }
    entry-get-filter-dto:               { $ref: './components/schemas/application-list-entries/entry-get-filter-dto.yaml' }
    entry-update-dto:                   { $ref: './components/schemas/application-list-entries/entry-update-dto.yaml' }
    entry-page:                         { $ref: './components/schemas/application-list-entries/entry-page.yaml' }
    # APPLICATION LIST ENTRY RESULT
    result-get-dto:                     { $ref: './components/schemas/application-list-entry-results/result-get-dto.yaml' }
    result-create-dto:                  { $ref: './components/schemas/application-list-entry-results/result-create-dto.yaml' }
    result-update-dto:                  { $ref: './components/schemas/application-list-entry-results/result-update-dto.yaml' }
    result-page:                        { $ref: './components/schemas/application-list-entry-results/result-page.yaml' }

    # COMMON
    problem:                            { $ref: './components/schemas/common/problem.yaml' }
    page:                               { $ref: './components/schemas/common/page.yaml' }
    sort:                               { $ref: './components/schemas/common/sort.yaml' }
    # COURT LOCATIONS
    court-location-get-summary-dto:     { $ref: './components/schemas/court-locations/court-location-get-summary-dto.yaml' }
    court-location-get-detail-dto:      { $ref: './components/schemas/court-locations/court-location-get-detail-dto.yaml' }
    court-location-page:                { $ref: './components/schemas/court-locations/court-location-page.yaml' }
    # CRIMINAL JUSTICE AREAS
    criminal-justice-area-get-dto:      { $ref: './components/schemas/criminal-justice-areas/criminal-justice-area-get-dto.yaml'}
    criminal-justice-area-page:         { $ref: './components/schemas/criminal-justice-areas/criminal-justice-area-page.yaml' }
    # FEE STATUS
    fee-status:                         { $ref: './components/schemas/fee-status/fee-status.yaml'}
    # PARTICIPANTS
    applicant:                          { $ref: './components/schemas/participants/applicant.yaml' }
    contact-details:                    { $ref: './components/schemas/participants/contact-details.yaml' }
    full-name:                          { $ref: './components/schemas/participants/full-name.yaml' }
    organisation:                       { $ref: './components/schemas/participants/organisation.yaml' }
    person:                             { $ref: './components/schemas/participants/person.yaml' }
    respondent:                         { $ref: './components/schemas/participants/respondent.yaml' }
    official:                           { $ref: './components/schemas/participants/official.yaml'}
    official-type:                      { $ref: './components/schemas/participants/official-type.yaml' }
    # RESULT CODES
    result-code-get-detail-dto:         { $ref: './components/schemas/result-codes/result-code-get-detail-dto.yaml' }
    result-code-get-summary-dto:        { $ref: './components/schemas/result-codes/result-code-get-summary-dto.yaml' }
    result-code-page:                   { $ref: './components/schemas/result-codes/result-code-page.yaml' }
    # STANDARD APPLICANTS
    standard-applicant-get-detail-dto:  { $ref: './components/schemas/standard-applicants/standard-applicant-get-detail-dto.yaml' }
    standard-applicant-get-summary-dto: { $ref: './components/schemas/standard-applicants/standard-applicant-get-summary-dto.yaml' }
    standard-applicant-page:            { $ref: './components/schemas/standard-applicants/standard-applicant-page.yaml' }

  responses:
    # ERRORS
    bad-request-error:     { $ref: './components/responses/bad-request-error.yaml' }
    unauthorized-error:    { $ref: './components/responses/unauthorized-error.yaml' }
    forbidden-error:       { $ref: './components/responses/forbidden-error.yaml' }
    not-found-error:       { $ref: './components/responses/not-found-error.yaml' }
    internal-server-error: { $ref: './components/responses/internal-server-error.yaml' }
    not-acceptable-error:  { $ref: './components/responses/not-acceptable-error.yaml' }
    conflict-error:        { $ref: './components/responses/conflict-error.yaml' }
