include:
  - docker-compose-deps.yml
services:
  app-reg-backend-functional:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: app-reg-backend:latest
    container_name: app-reg-poc-backend
    environment:
      # these environment variables are used by java-logging library
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/appreg-db
      - SPRING_DATASOURCE_USERNAME=app_reg_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=functional
      - APP_REG_SCHEMA=functionalschema
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_AUDIENCE_ID=${AZURE_AUDIENCE_ID}
      - AZURE_ISSUER=${AZURE_ISSUER}
    ports:
      - "4550:4550"
      - "5005:5005"
    depends_on:
      - postgres
    profiles: [functionaltesting]

  app-reg-backend-testing:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: app-reg-backend:latest
    container_name: app-reg-poc-backend
    environment:
      # these environment variables are used by java-logging library
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/appreg-db
      - SPRING_DATASOURCE_USERNAME=app_reg_user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=testing
      - APP_REG_SCHEMA=testingschema
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_AUDIENCE_ID=${AZURE_AUDIENCE_ID}
      - AZURE_ISSUER=${AZURE_ISSUER}
    ports:
      - "4550:4550"
      - "5005:5005"
    depends_on:
      - postgres
    profiles: [testing]
