version: '2.1'
include:
  - docker-compose-deps.yml
services:
  app-reg-poc-backend:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: app-reg-poc-backend:latest
    container_name: app-reg-poc-backend
    environment:
      # these environment variables are used by java-logging library
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app_reg_db
      - SPRING_DATASOURCE_USERNAME=app_reg_user
      - SPRING_DATASOURCE_PASSWORD=password
      - ENABLE_DB_MIGRATE=true
    ports:
      - "4550:4550"
      - "5005:5005"
    depends_on:
      - postgres
