apiVersion: v2
appVersion: 3.2.0
dependencies:
- name: library
  repository: oci://hmctspublic.azurecr.io/helm
  version: 2.2.2
description: A Helm chart for HMCTS nodejs apps
icon: https://nodejs.org/static/images/logos/nodejs-new-pantone-black.png
keywords:
- node
- javascript
- nodejs
name: nodejs
sources:
- https://github.com/hmcts/chart-nodejs
version: 3.2.0
