server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus, rest-implementation-status

springdoc:
  writer-with-order-by-keys: true

spring:
  http:
    converters:
      preferred-json-mapper: true
  # Continue to use Jackson 2 for now
  jackson:
    use-jackson2-defaults: true
  data:
    web:
      pageable:
        one-indexed-parameters: false
        # The page name parameters do not make any difference as they are
        # hard coded into the open api spec
        page-parameter: page
        size-parameter: pageSize
        default-page-size: 10
        max-page-size: 100
      sort:
        sort-parameter: sort
  config:
    import: "optional:configtree:/mnt/secrets/appreg/"
  application:
    name: Application Registration API
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:appreg-db}
    username: ${POSTGRES_USER:app_reg_user}
    password: ${POSTGRES_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${spring.sql.init.schema-locations}
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: ${ENABLE_DB_MIGRATE:false}
    locations: classpath:/migrations
    default-schema: ${spring.sql.init.schema-locations}
    mixed: true
  sql:
    init:
      mode: never
      schema-locations: ${APP_REG_SCHEMA:appreg}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER:https://login.microsoftonline.com/${spring.security.oauth2.resourceserver.jwt.tenant}/v2.0}
          audiences:
          - ${AZURE_AUDIENCE_ID:00000000-0000-0000-0000-000000000000}
          - ${AZURE_AUDIENCE_ID_URI:api://${AZURE_AUDIENCE_ID}}
          tenant: ${AZURE_TENANT_ID:00000000-0000-0000-0000-000000000000}
  mvc:
    static-path-pattern: /specs/**

app:
  timezone: "Europe/London"

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}


appreg:
  audit:
    diff:
      enable-complex-diff: true


