server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  writer-with-order-by-keys: true

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: pageSize
        default-page-size: 10
        max-page-size: 100
  config:
    import: "optional:configtree:/mnt/secrets/appreg/"
  application:
    name: Application Registration API
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:appreg-db}
    username: ${POSTGRES_USER:appreg_user}
    password: ${POSTGRES_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: appreg
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${azure-tenant-id}/v2.0
          audiences: ${azure-audience-id}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
