# Flyway configuration for local environment. Useful for functional testing as well as integration testing.
spring:
  flyway:
    enabled: true
    locations: classpath:/migrations,/baseline
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    mixed: true
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${wiremock.server.port}/discovery/v2.0/keys
logging:
  level:
    org.springframework.security: TRACE
