# Flyway configuration for local environment. Useful for functional testing as well as integration testing.
spring:
  flyway:
    enabled: true
    locations: classpath:/migrations,/data_population_test
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
    mixed: true
    baseline-on-migrate: true
  sql:
    init:
      # Ensure that the test db schema is created for testing. This
      # helps us catch bugs in the flyway scripts where a schema name is
      # explicitly defined.
      schema-locations: ${APP_REG_SCHEMA:testschema}
logging:
  level:
    org.springframework.security: TRACE

