server:
  port: 4550
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      # group:
      #  readiness:
      #   include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/appreg/"
  application:
    name: Application Registration API
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:appreg_db}
    username: ${POSTGRES_USER:appreg_user}
    password: ${POSTGRES_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/.well-known/jwks.json
        # The below is the default issuer URI for Azure AD v2.0. When connecting to AAD we will need to set the issuer URI to the AAD tenant.
        # issuer-uri: https://login.microsoftonline.com/{your-tenant-id}/v2.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
