package uk.gov.hmcts.appregister.common.health;

import java.io.File;
import java.lang.reflect.Method;
import java.net.JarURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.jar.JarFile;
import java.util.stream.Collectors;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.actuate.endpoint.OperationResponseBody;
import org.springframework.boot.actuate.endpoint.annotation.Endpoint;
import org.springframework.boot.actuate.endpoint.annotation.ReadOperation;
import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;
import org.springframework.core.annotation.AnnotatedElementUtils;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * This is a health indicator that publishes which endpoints have been implemented by using java
 * reflection together with Spring component scanning.
 */
@Component
@Endpoint(id = "rest-implementation-status")
@Slf4j
public class RestImplementedStatusHealthIndicator {

    // markers for implemented and not implemented endpoints
    public static final String IMPLEMENTED = "IMPLEMENTED: Ready for Test";
    public static final String NOT_IMPLEMENTED = "**** NOT_IMPLEMENTED: Not Ready for Test ****";

    // base package to search for implementing controllers
    private static final String BASE_PACKAGE = "uk.gov.hmcts.appregister";

    // base package for api interfaces generated by the open api spec
    // generation process
    private static final String PACKAGE_NAME_API_INTERFACE = BASE_PACKAGE + ".generated.api";

    /**
     * The core read operation that is used to publish the data.
     *
     * @return The details of the endpoint that relates to implemented and non implemented
     *     endpoints.
     */
    @ReadOperation
    public Map<String, Object> status() throws Exception {
        // Gets the controller methods for all interfaces
        List<ApiMethod> methodForControllerApiInterfaces =
                findAllInterfacesUsingClassLoader(PACKAGE_NAME_API_INTERFACE);

        Map<String, Object> details =
                getImplementedAndUnimplementedApiDetails(methodForControllerApiInterfaces);

        return OperationResponseBody.of(details);
    }

    /**
     * Tries to determine what is implemented.
     *
     * @param interfaceControllerMethods The controller methods for the API interfaces
     * @return The map listing the api calls that are and are not implemented
     */
    public Map<String, Object> getImplementedAndUnimplementedApiDetails(
            List<ApiMethod> interfaceControllerMethods) throws Exception {
        var scanner = new ClassPathScanningCandidateComponentProvider(false);
        scanner.addIncludeFilter((mr, mrf) -> true); // include everything

        // gets the interface names
        Set<String> interfaceForApi =
                interfaceControllerMethods.stream()
                        .map(ApiMethod::getApiClassName)
                        .collect(Collectors.toSet());

        // list of the processed api classes
        List<String> processedApiClasses = new ArrayList<>();

        // lists of implemented and unimplemented endpoints
        List<ApiMethod> implementedEndpoints = new ArrayList<>();
        List<ApiMethod> unImplementedEndpoints = new ArrayList<>();

        // scan all active spring components
        scanner.findCandidateComponents(BASE_PACKAGE).stream()
                .forEach(
                        bd -> {
                            try {
                                Class component = Class.forName(bd.getBeanClassName());

                                // gets the interface for all components
                                Class[] interfaces = component.getInterfaces();

                                // look through and match on all interfaces
                                for (Class<?> interf : interfaces) {
                                    // ensure we have an interface for the component
                                    if (interfaces.length > 0) {

                                        // check the component matches the api names
                                        if (interfaceForApi.contains(interf.getCanonicalName())) {

                                            // store the processed api to determine the
                                            // unimplemented
                                            // apis at the end
                                            processedApiClasses.add(interf.getCanonicalName());

                                            // gets the api methods of the component
                                            List<ApiMethod> controllerMethodsForComponent =
                                                    getControllerMethod(component);
                                            // loop through the API component methods and check if
                                            // the
                                            // component has an
                                            // implementation for it.
                                            for (ApiMethod methodName :
                                                    controllerMethodsForComponent) {
                                                // check if the component is in the list of
                                                // generated
                                                // API interfaces
                                                if (interfaceControllerMethods.contains(
                                                        methodName)) {
                                                    implementedEndpoints.add(methodName);

                                                    // make the api as being implemented
                                                    interfaceControllerMethods.stream()
                                                            .filter(e -> e.equals(methodName))
                                                            .toList()
                                                            .getFirst()
                                                            .setMarkAsImplemented(true);
                                                }
                                            }
                                        }
                                    }
                                }
                            } catch (ClassNotFoundException cnf) {
                                log.error("The class could not be found", cnf);
                            }
                        });

        // find unprocessed endpoints
        for (ApiMethod apiMethod : interfaceControllerMethods) {
            if (!apiMethod.isMarkAsImplemented) {
                unImplementedEndpoints.add(apiMethod);
            }
        }

        // collect unimplemented interfaces
        interfaceForApi.removeAll(processedApiClasses);
        for (String api : interfaceForApi) {
            for (Method method : Class.forName(api).getMethods()) {
                if (ApiMethod.isHttpExposedMethod(method)) {
                    ApiMethod controllerMethod = new ApiMethod(method);
                    unImplementedEndpoints.add(controllerMethod);
                }
            }
        }

        return getImplementedAndUnimplementedEndpoints(
                implementedEndpoints, unImplementedEndpoints);
    }

    /**
     * converts all implemented and unimplemented endpoints to a map for publishing.
     *
     * @param implementedEndpoints The list of implemented endpoints
     * @param unImplementedEndpoints The list of unimplemented endpoints
     * @return The map of endpoints and their implementation status
     */
    private Map<String, Object> getImplementedAndUnimplementedEndpoints(
            List<ApiMethod> implementedEndpoints, List<ApiMethod> unImplementedEndpoints) {
        Map<String, Object> details = new LinkedHashMap<>();

        implementedEndpoints.stream()
                .forEach(
                        controllerMethod -> {
                            details.put(controllerMethod.getApiString(), IMPLEMENTED);
                        });

        unImplementedEndpoints.stream()
                .forEach(
                        controllerMethod -> {
                            details.put(controllerMethod.getApiString(), NOT_IMPLEMENTED);
                        });
        return details;
    }

    /**
     * finds all of the classes under package.
     *
     * @param packageName The package name
     * @return The methods
     */
    public List<ApiMethod> findAllInterfacesUsingClassLoader(String packageName) throws Exception {
        List<Class> classes =
                findClasses(packageName).stream()
                        .filter(Class::isInterface)
                        .collect(Collectors.toList());

        List<ApiMethod> methods = new ArrayList<>();

        // loop through the classes and get all of the methods for each class and add them to the
        // list of methods
        for (Class clz : classes) {
            methods.addAll(
                    Arrays.stream(clz.getMethods())
                            .filter(method -> ApiMethod.isHttpExposedMethod(method))
                            .map(ApiMethod::new)
                            .collect(Collectors.toList()));
        }
        return methods;
    }

    /**
     * gets all api methods that are associated with the class. Api methods are defined as methods
     * that are exposed as endpoints by having a RequestMapping annotation on the method or the
     * interface method (if it exists).
     *
     * @return The api methods for the class.
     */
    private List<ApiMethod> getControllerMethod(Class clzz) {
        List<ApiMethod> methods = new ArrayList<>();

        methods.addAll(
                Arrays.stream(clzz.getDeclaredMethods())
                        .filter(method -> ApiMethod.isHttpExposedMethod(method))
                        .map(ApiMethod::new)
                        .collect(Collectors.toList()));
        return methods;
    }

    /**
     * gets a class from inside the package.
     *
     * @param className The class name to get
     * @param packageName The package name to search in
     * @return The class if it is found, null otherwise
     */
    private Class getClass(String className, String packageName) {
        try {
            return Class.forName(
                    packageName + "." + className.substring(0, className.lastIndexOf('.')));
        } catch (ClassNotFoundException e) {
            // handle the exception
        }
        return null;
    }

    /**
     * This function gets classes under a package. This is needed for classes to be found when
     * running in docker.
     *
     * @param packageName Take a package name and get the classes
     * @return The classes under the package
     */
    public static Set<Class<?>> findClasses(String packageName) throws Exception {
        Set<Class<?>> classes = new HashSet<>();
        String path = packageName.replace('.', '/');

        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        Enumeration<URL> resources = classLoader.getResources(path);

        while (resources.hasMoreElements()) {
            URL resource = resources.nextElement();

            if (resource.getProtocol().equals("file")) {
                File dir = new File(resource.toURI());
                for (File file : dir.listFiles()) {
                    if (file.getName().endsWith(".class")) {
                        String className = packageName + "." + file.getName().replace(".class", "");
                        classes.add(Class.forName(className));
                    }
                }
            }

            if (resource.getProtocol().equals("jar")) {
                JarURLConnection conn = (JarURLConnection) resource.openConnection();
                try (JarFile jar = conn.getJarFile()) {
                    jar.stream()
                            .filter(
                                    entry ->
                                            entry.getName().startsWith(path)
                                                    && entry.getName().endsWith(".class"))
                            .forEach(
                                    entry -> {
                                        String className =
                                                entry.getName()
                                                        .replace("/", ".")
                                                        .replace(".class", "");
                                        try {
                                            classes.add(Class.forName(className));
                                        } catch (ClassNotFoundException ignored) {
                                            log.warn("Error", ignored);
                                        }
                                    });
                }
            }
        }

        return classes;
    }

    /** An implementation of a controller method that allows us to extract the api details. */
    @EqualsAndHashCode
    @Getter
    class ApiMethod {
        @EqualsAndHashCode.Exclude private Method method;

        @EqualsAndHashCode.Include private String apiMethodSig;

        @EqualsAndHashCode.Include private String className;

        /** Allows us to mark if this has been implemented. */
        private boolean isMarkAsImplemented = false;

        public void setMarkAsImplemented(boolean markAsImplemented) {
            isMarkAsImplemented = markAsImplemented;
        }

        public ApiMethod(Method method) {
            this.method = method;
            apiMethodSig = getMethod(method).toString();
            className = getApiClassName();
        }

        /**
         * gets the api class name.
         *
         * @return The api class name
         */
        public String getApiClassName() {
            if (method.getDeclaringClass().isInterface()) {
                className = method.getDeclaringClass().getCanonicalName();
            } else {
                // assumes the first interface is the API interface. This is a fair assumption
                // as our controllers only implement one interface
                className = method.getDeclaringClass().getInterfaces()[0].getCanonicalName();
            }
            return className;
        }

        @Override
        public String toString() {
            return method.getDeclaringClass() + " " + method;
        }

        /**
         * Determines if the method is an HTTP exposed method by checking if it has a RequestMapping
         * annotation. This searches the method as well as the interface method (if it exists) for
         * the annotation.
         *
         * @return true if the method is an HTTP exposed method, false otherwise
         */
        public static boolean isHttpExposedMethod(Method method) {
            return getRequestMapping(method) != null;
        }

        /**
         * gets the request mapping annotation for the method. This searches the method as well as
         * the interface method (if it exists) for the annotation.
         *
         * @param method The method to get the request mapping annotation for
         * @return The request mapping annotation if it exists, null otherwise
         */
        public static RequestMapping getRequestMapping(Method method) {
            RequestMapping requestMapping =
                    AnnotatedElementUtils.findMergedAnnotation(method, RequestMapping.class);

            if (requestMapping == null) {
                // if the method is an implemented method look to the interface
                Class[] declaringClass = method.getDeclaringClass().getInterfaces();
                if (declaringClass.length > 0) {

                    // try all interfaces for the method and return the annotation
                    // if we find it on any of the interfaces
                    for (Class interf : declaringClass) {
                        try {
                            Method interfaceMethod =
                                    interf.getMethod(method.getName(), method.getParameterTypes());

                            // if we have found the interface method then return the annotation
                            if (interfaceMethod != null) {
                                requestMapping =
                                        AnnotatedElementUtils.findMergedAnnotation(
                                                interfaceMethod, RequestMapping.class);
                                return requestMapping;
                            }
                        } catch (NoSuchMethodException e) {
                            log.error("Method could not be found", e);
                        }
                    }
                }
            }

            return requestMapping;
        }

        /**
         * gets the associated method for this method. If the method is an implemented method, this
         * will return the interface method, otherwise it will return the method itself.
         *
         * @param method The method to get the associated method for
         * @return The associated method for this method if it is declared in the interface
         */
        private Method getMethod(Method method) {
            Class[] declaringClass = method.getDeclaringClass().getInterfaces();
            if (declaringClass.length > 0) {

                try {
                    return declaringClass[0].getMethod(
                            method.getName(), method.getParameterTypes());
                } catch (NoSuchMethodException e) {
                    log.error("Method could not be found", e);
                }
            }

            return method;
        }

        /**
         * gets an api string for this method.
         *
         * @return The request annotation information for this endpoint
         */
        public String getApiString() {
            RequestMapping requestMapping = getRequestMapping(method);

            if (requestMapping != null && requestMapping.method().length > 0) {
                String method = requestMapping.method()[0].toString();
                String url = requestMapping.value()[0].toString();

                return method + " " + url;
            }

            return "n/a";
        }
    }
}
