spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:${wiremock.server.port}/discovery/v2.0/keys

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.*: DEBUG
    root: debug
appreg:
  audit:
    diff:
      enable-complex-diff: true
