  CREATE OR REPLACE FORCE VIEW "APPREGISTER"."V_APPLICATION_CODES_NOCLOB" ("AC_ID", "APPLICATION_CODE", "APPLICATION_CODE_TITLE", "APPLICATION_CODE_WORDING", "APPLICATION_LEGISLATION", "FEE_DUE", "APPLICATION_CODE_RESPONDENT", "AC_DESTINATION_EMAIL_ADDRESS_1", "AC_DESTINATION_EMAIL_ADDRESS_2", "APPLICATION_CODE_START_DATE", "APPLICATION_CODE_END_DATE", "BULK_RESPONDENT_ALLOWED", "VERSION", "CHANGED_BY", "CHANGED_DATE", "USER_NAME", "AC_FEE_REFERENCE") AS
  SELECT AC_ID
,      APPLICATION_CODE
,      APPLICATION_CODE_TITLE
,      dbms_lob.substr(APPLICATION_CODE_WORDING,4000,1) application_code_wording

,      dbms_lob.substr(APPLICATION_LEGISLATION,4000,1)  application_legislation
,      FEE_DUE
,      APPLICATION_CODE_RESPONDENT
,      AC_DESTINATION_EMAIL_ADDRESS_1
,      AC_DESTINATION_EMAIL_ADDRESS_2
,      APPLICATION_CODE_START_DATE
,      APPLICATION_CODE_END_DATE
,      BULK_RESPONDENT_ALLOWED
,      VERSION
,      CHANGED_BY
,      CHANGED_DATE
,      USER_NAME
,      AC_FEE_REFERENCE
FROM   application_codes
