  CREATE OR REPLACE FORCE VIEW "APPREGISTER"."V_RESOLUTION_CODES_NOCLOB" ("RC_ID", "RESOLUTION_CODE", "RESOLUTION_CODE_TITLE", "RESOLUTION_CODE_WORDING", "RESOLUTION_LEGISLATION", "RC_DESTINATION_EMAIL_ADDRESS_1", "RC_DESTINATION_EMAIL_ADDRESS_2", "RESOLUTION_CODE_START_DATE", "RESOLUTION_CODE_END_DATE", "VERSION", "CHANGED_BY", "CHANGED_DATE", "USER_NAME") AS
  SELECT RC_ID
,      RESOLUTION_CODE
,      RESOLUTION_CODE_TITLE
,      dbms_lob.substr(RESOLUTION_CODE_WORDING,4000,1)  RESOLUTION_CODE_WORDING
,      dbms_lob.substr(RESOLUTION_LEGISLATION,4000,1)   RESOLUTION_LEGISLATION
,      RC_DESTINATION_EMAIL_ADDRESS_1
,      RC_DESTINATION_EMAIL_ADDRESS_2
,      RESOLUTION_CODE_START_DATE
,      RESOLUTION_CODE_END_DATE
,      VERSION
,      CHANGED_BY
,      CHANGED_DATE
,      USER_NAME
FROM   resolution_codes
