package uk.gov.hmcts.appregister.applicationlist.mapper;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;

import org.mockito.junit.jupiter.MockitoExtension;

import uk.gov.hmcts.appregister.common.entity.ApplicationList;
import uk.gov.hmcts.appregister.common.entity.CriminalJusticeArea;
import uk.gov.hmcts.appregister.common.entity.NationalCourtHouse;
import uk.gov.hmcts.appregister.common.service.DateTimeService;
import uk.gov.hmcts.appregister.generated.model.ApplicationListCreateDto;
import uk.gov.hmcts.appregister.generated.model.ApplicationListGetDetailDto;
import uk.gov.hmcts.appregister.generated.model.ApplicationListStatus;

/**
 * Unit tests for {@link ApplicationListMapper}. We test the generated implementation directly
 * and inject a mock {@link DateTimeService} to control normalization behavior.
 */
@ExtendWith(MockitoExtension.class)
class ApplicationListMapperTest {

    // Generated by MapStruct; available on the test classpath after compile
    @InjectMocks
    private ApplicationListMapperImpl mapper;

    @Mock
    private DateTimeService dateTimeService;

    // ---------- Mapping: toCreateEntityWithCourt ----------

    @Nested
    class ToCreateEntityWithCourtTests {

        @Test
        void toCreateEntityWithCourt_validDtoWithCourt_returnsValidEntity() {
            // Given
            var dto = new ApplicationListCreateDto()
                .date(LocalDate.of(2025, 9, 17))
                .time("10:30")
                .description("Morning session")
                .status(ApplicationListStatus.OPEN)
                .courtLocationCode("LOC123")
                .durationHours(2)
                .durationMinutes(45);

            var court = NationalCourtHouse.builder()
                .name("Bath Magistrates Court")
                .courtLocationCode("LOC123")
                .build();

            // Mock Date/Time normalization now handled by DateTimeService
            when(dateTimeService.normalizeDate(LocalDate.of(2025, 9, 17)))
                .thenReturn(LocalDateTime.of(2025, 9, 17, 0, 0));
            when(dateTimeService.normalizeTime("10:30"))
                .thenReturn(LocalDateTime.of(2025, 9, 17, 10, 30, 0));

            // When
            ApplicationList entity = mapper.toCreateEntityWithCourt(dto, court);

            // Then
            assertNull(entity.getPk());
            assertNull(entity.getUuid());
            assertNull(entity.getVersion());
            assertNull(entity.getCreatedUser());

            assertEquals("LOC123", entity.getCourtCode());
            assertEquals("Bath Magistrates Court", entity.getCourtName());
            assertNull(entity.getCja());
            assertNull(entity.getOtherLocation());
            assertEquals("Morning session", entity.getDescription());
            assertEquals("OPEN", entity.getStatus());
            assertEquals(LocalDateTime.of(2025, 9, 17, 0, 0), entity.getDate());
            assertEquals(LocalDateTime.of(2025, 9, 17, 10, 30, 0), entity.getTime());
            assertEquals(2, entity.getDurationHours());
            assertEquals(45, entity.getDurationMinutes());
        }
    }

    // ---------- Mapping: toCreateEntityWithCja ----------

    @Nested
    class ToCreateEntityWithCjaTests {

        @Test
        void toCreateEntityWithCja_validDtoWithCja_returnsValidEntity() {
            // Given
            var dto = new ApplicationListCreateDto()
                .date(LocalDate.of(2025, 9, 18))
                .time("14:05:07")
                .description("Afternoon session")
                .otherLocationDescription("Temporary Courtroom at Town Hall")
                .status(ApplicationListStatus.OPEN)
                .durationHours(1)
                .durationMinutes(15);

            var cja = CriminalJusticeArea.builder()
                .id(123L)
                .code("CJA001")
                .description("Example CJA")
                .build();

            when(dateTimeService.normalizeDate(LocalDate.of(2025, 9, 18)))
                .thenReturn(LocalDateTime.of(2025, 9, 18, 0, 0));
            when(dateTimeService.normalizeTime("14:05:07"))
                .thenReturn(LocalDateTime.of(2025, 9, 18, 14, 5, 7));

            // When
            ApplicationList entity = mapper.toCreateEntityWithCja(dto, cja);

            // Then
            assertNull(entity.getPk());
            assertNull(entity.getUuid());
            assertNull(entity.getVersion());
            assertNull(entity.getCreatedUser());
            assertNull(entity.getCourtCode());
            assertNull(entity.getCourtName());

            assertNotNull(entity.getCja());
            assertEquals(123L, entity.getCja().getId());
            assertEquals("CJA001", entity.getCja().getCode());
            assertEquals("Temporary Courtroom at Town Hall", entity.getOtherLocation());
            assertEquals("Afternoon session", entity.getDescription());
            assertEquals("OPEN", entity.getStatus());
            assertEquals(LocalDateTime.of(2025, 9, 18, 0, 0), entity.getDate());
            assertEquals(LocalDateTime.of(2025, 9, 18, 14, 5, 7), entity.getTime());
            assertEquals(1, entity.getDurationHours());
            assertEquals(15, entity.getDurationMinutes());
        }
    }

    // ---------- Mapping: toGetDetailDto ----------

    @Nested
    class ToGetDetailDtoTests {

        @Test
        void toGetDetailDto_passedValidEntityWithNullCja_returnsValidDto() {
            UUID id = UUID.fromString("3fa85f64-5717-4562-b3fc-2c963f66afa6");

            var appList = ApplicationList.builder()
                .pk(999L)
                .uuid(id)
                .description("Morning session for traffic-related applications")
                .status(ApplicationListStatus.OPEN)
                .courtCode("LOC123")
                .courtName("Bath Magistrates Court")
                .date(LocalDateTime.of(2025, 9, 17, 0, 0))
                .time(LocalDateTime.of(2025, 9, 17, 10, 30, 0))
                .durationHours((short) 2)
                .durationMinutes((short) 30)
                .version(3L)
                .build();

            // MapStruct calls DateTimeService.toTimeString(appList.time)
            when(dateTimeService.toTimeString(LocalDateTime.of(2025, 9, 17, 10, 30, 0)))
                .thenReturn("10:30");

            // When
            ApplicationListGetDetailDto dto = mapper.toGetDetailDto(appList, null);

            // Then
            assertNull(dto.getCjaCode());
            assertNull(dto.getOtherLocationDescription());

            assertEquals(id, dto.getId());
            assertEquals(LocalDate.of(2025, 9, 17), dto.getDate());
            assertEquals("10:30", dto.getTime());
            assertEquals("Morning session for traffic-related applications", dto.getDescription());
            assertEquals(ApplicationListStatus.OPEN, dto.getStatus());
            assertEquals("LOC123", dto.getCourtCode());
            assertEquals("Bath Magistrates Court", dto.getCourtName());
            assertEquals(2, dto.getDurationHours());
            assertEquals(30, dto.getDurationMinutes());
            assertEquals(3L, dto.getVersion());
        }
    }
}
