  CREATE TABLE "LIBRA"."ADDRESSES"
   (    "ADR_ID" NUMBER(10,0) NOT NULL ENABLE,
        "LINE1" VARCHAR2(35 CHAR),
        "LINE2" VARCHAR2(35 CHAR),
        "LINE3" VARCHAR2(35 CHAR),
        "LINE4" VARCHAR2(35 CHAR),
        "LINE5" VARCHAR2(35 CHAR),
        "POSTCODE" VARCHAR2(8 CHAR),
        "START_DATE" DATE NOT NULL ENABLE,
        "END_DATE" DATE,
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "MCC_MCC_ID" NUMBER(10,0),
         CONSTRAINT "ADR_PK" PRIMARY KEY ("ADR_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE,
         CONSTRAINT "ADR_DATE_RANGE_CHK" CHECK (
/* start_date not null and end date >= start date or null
 and both are dates with 00:00 time */
start_date = TRUNC(start_date) AND
( end_date IS NULL OR
( end_date = TRUNC(end_date)
AND end_date >= start_date
)
)) ENABLE,
         SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
         SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
         SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS,
         SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS,
         CONSTRAINT "ADR_MCC_FK" FOREIGN KEY ("MCC_MCC_ID")
          REFERENCES "LIBRA"."MAG_COURT_COMMITTEES" ("MCC_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
