  CREATE TABLE "APPREGISTER"."APP_LIST_ENTRY_RESOLUTIONS"
   (    "ALER_ID" NUMBER NOT NULL ENABLE,
        "RC_RC_ID" NUMBER NOT NULL ENABLE,
        "ALE_ALE_ID" NUMBER NOT NULL ENABLE,
        "AL_ENTRY_RESOLUTION_WORDING" CLOB NOT NULL ENABLE,
        "AL_ENTRY_RESOLUTION_OFFICER" VARCHAR2(1000 CHAR) NOT NULL ENABLE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
         CONSTRAINT "APP_LIST_ENTRY_RESOLUTIONS_PK" PRIMARY KEY ("ALER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "ALER_ALE_FK" FOREIGN KEY ("ALE_ALE_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LIST_ENTRIES" ("ALE_ID") ENABLE,
         CONSTRAINT "ALER_RC_FK" FOREIGN KEY ("RC_RC_ID")
          REFERENCES "APPREGISTER"."RESOLUTION_CODES" ("RC_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
 LOB ("AL_ENTRY_RESOLUTION_WORDING") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
