  CREATE TABLE "APPREGISTER"."APP_LIST_ENTRY_FEE_STATUS"
   (    "ALEFS_ID" NUMBER NOT NULL ENABLE,
        "ALEFS_ALE_ID" NUMBER NOT NULL ENABLE,
        "ALEFS_PAYMENT_REFERENCE" VARCHAR2(15 CHAR),
        "ALEFS_FEE_STATUS" VARCHAR2(1 CHAR) NOT NULL ENABLE,
        "ALEFS_FEE_STATUS_DATE" DATE NOT NULL ENABLE,
        "ALEFS_VERSION" NUMBER NOT NULL ENABLE,
        "ALEFS_CHANGED_BY" NUMBER NOT NULL ENABLE,
        "ALEFS_CHANGED_DATE" DATE NOT NULL ENABLE,
        "ALEFS_USER_NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE,
        "ALEFS_STATUS_CREATION_DATE" DATE,
         CONSTRAINT "ALEFS_ID_PK" PRIMARY KEY ("ALEFS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "ALEFS_FEE_STATUS_CHK" CHECK (ALEFS_FEE_STATUS IN ('D','P','R','U')
) ENABLE,
         CONSTRAINT "ALEFS_ID_FK" FOREIGN KEY ("ALEFS_ALE_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LIST_ENTRIES" ("ALE_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
