  CREATE TABLE "APPREGISTER"."APP_LIST_ENTRY_FEE_ID"
   (    "ALE_ALE_ID" NUMBER NOT NULL ENABLE,
        "FEE_FEE_ID" NUMBER NOT NULL ENABLE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE,
         CONSTRAINT "ALEFI_PK" PRIMARY KEY ("ALE_ALE_ID", "FEE_FEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "ALEFI_ALE_FK" FOREIGN KEY ("ALE_ALE_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LIST_ENTRIES" ("ALE_ID") ENABLE,
         CONSTRAINT "ALEFI_FEE_FK" FOREIGN KEY ("FEE_FEE_ID")
          REFERENCES "APPREGISTER"."FEE" ("FEE_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
