  CREATE TABLE "APPREGISTER"."APP_LIST_ENTRY_OFFICIAL"
   (    "ALEO_ID" NUMBER NOT NULL ENABLE,
        "ALE_ALE_ID" NUMBER NOT NULL ENABLE,
        "TITLE" VARCHAR2(100 CHAR),
        "FORENAME" VARCHAR2(100 CHAR),
        "SURNAME" VARCHAR2(100 CHAR),
        "OFFICIAL_TYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE,
         CONSTRAINT "APP_LIST_ENTRY_OFFICIAL_PK" PRIMARY KEY ("ALEO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "ALEO_OFFICIAL_TYPE_CHK" CHECK (official_type IN ('C','M')) ENABLE,
         CONSTRAINT "ALEO_ID_FK" FOREIGN KEY ("ALE_ALE_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LIST_ENTRIES" ("ALE_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
