  CREATE TABLE "APPREGISTER"."APPLICATION_REGISTER"
   (    "AR_ID" NUMBER NOT NULL ENABLE,
        "AL_AL_ID" NUMBER NOT NULL ENABLE,
        "TEXT" CLOB,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
         CONSTRAINT "APPLICATION_REGISTER_PK" PRIMARY KEY ("AR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "AR_AL_FK" FOREIGN KEY ("AL_AL_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LISTS" ("AL_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
 LOB ("TEXT") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
