  CREATE TABLE "APPREGISTER"."APPLICATION_LISTS"
   (    "AL_ID" NUMBER NOT NULL ENABLE,
        "APPLICATION_LIST_STATUS" VARCHAR2(6 CHAR),
        "APPLICATION_LIST_DATE" DATE NOT NULL ENABLE,
        "APPLICATION_LIST_TIME" TIMESTAMP (6) NOT NULL ENABLE,
        "COURTHOUSE_CODE" VARCHAR2(10 CHAR),
        "OTHER_COURTHOUSE" VARCHAR2(200 CHAR),
        "LIST_DESCRIPTION" VARCHAR2(200 CHAR) NOT NULL ENABLE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
        "COURTHOUSE_NAME" VARCHAR2(200 CHAR),
        "DURATION_HOUR" NUMBER(2,0),
        "DURATION_MINUTE" NUMBER(2,0),
        "CJA_CJA_ID" NUMBER,
         CONSTRAINT "APPLICATION_LISTS_PK" PRIMARY KEY ("AL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "AL_CJA_FK" FOREIGN KEY ("CJA_CJA_ID")
          REFERENCES "APPREGISTER"."CRIMINAL_JUSTICE_AREA" ("CJA_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
