  CREATE TABLE "APPREGISTER"."APPLICATION_CODES"
   (    "AC_ID" NUMBER NOT NULL ENABLE,
        "APPLICATION_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
        "APPLICATION_CODE_TITLE" VARCHAR2(500 CHAR) NOT NULL ENABLE,
        "APPLICATION_CODE_WORDING" CLOB NOT NULL ENABLE,
        "APPLICATION_LEGISLATION" CLOB,
        "FEE_DUE" CHAR(1 CHAR) NOT NULL ENABLE,
        "APPLICATION_CODE_RESPONDENT" CHAR(1 CHAR) NOT NULL ENABLE,
        "AC_DESTINATION_EMAIL_ADDRESS_1" VARCHAR2(253 CHAR),
        "AC_DESTINATION_EMAIL_ADDRESS_2" VARCHAR2(253 CHAR),
        "APPLICATION_CODE_START_DATE" DATE NOT NULL ENABLE,
        "APPLICATION_CODE_END_DATE" DATE,
        "BULK_RESPONDENT_ALLOWED" CHAR(1 CHAR) NOT NULL ENABLE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
        "AC_FEE_REFERENCE" VARCHAR2(12 CHAR),
         CONSTRAINT "APPLICATION_CODES_PK" PRIMARY KEY ("AC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
 LOB ("APPLICATION_CODE_WORDING") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
 LOB ("APPLICATION_LEGISLATION") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
