  CREATE TABLE "APPREGISTER"."APPLICATION_LIST_ENTRIES"
   (    "ALE_ID" NUMBER NOT NULL ENABLE,
        "AL_AL_ID" NUMBER NOT NULL ENABLE,
        "SA_SA_ID" NUMBER,
        "AC_AC_ID" NUMBER NOT NULL ENABLE,
        "A_NA_ID" NUMBER,
        "R_NA_ID" NUMBER,
        "NUMBER_OF_BULK_RESPONDENTS" NUMBER(4,0),
        "APPLICATION_LIST_ENTRY_WORDING" CLOB NOT NULL ENABLE,
        "CASE_REFERENCE" VARCHAR2(15 CHAR),
        "ACCOUNT_NUMBER" VARCHAR2(20 CHAR),
        "ENTRY_RESCHEDULED" CHAR(1 CHAR) NOT NULL ENABLE,
        "NOTES" VARCHAR2(4000 CHAR),
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "BULK_UPLOAD" VARCHAR2(1 CHAR),
        "USER_NAME" VARCHAR2(250 CHAR),
        "SEQUENCE_NUMBER" NUMBER(4,0) NOT NULL ENABLE,
        "TCEP_STATUS" VARCHAR2(2 CHAR),
        "MESSAGE_UUID" VARCHAR2(36 CHAR),
        "RETRY_COUNT" VARCHAR2(36 CHAR),
        "LODGEMENT_DATE" DATE NOT NULL ENABLE,
         CONSTRAINT "APPLICATION_LIST_ENTRIES_PK" PRIMARY KEY ("ALE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE,
         CONSTRAINT "ALE_AC_FK" FOREIGN KEY ("AC_AC_ID")
          REFERENCES "APPREGISTER"."APPLICATION_CODES" ("AC_ID") ENABLE,
         CONSTRAINT "ALE_AL_FK" FOREIGN KEY ("AL_AL_ID")
          REFERENCES "APPREGISTER"."APPLICATION_LISTS" ("AL_ID") ENABLE,
         CONSTRAINT "ALE_A_NA_FK" FOREIGN KEY ("A_NA_ID")
          REFERENCES "APPREGISTER"."NAME_ADDRESS" ("NA_ID") ENABLE,
         CONSTRAINT "ALE_R_NA_FK" FOREIGN KEY ("R_NA_ID")
          REFERENCES "APPREGISTER"."NAME_ADDRESS" ("NA_ID") ENABLE,
         CONSTRAINT "ALE_SA_FK" FOREIGN KEY ("SA_SA_ID")
          REFERENCES "APPREGISTER"."STANDARD_APPLICANTS" ("SA_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
 LOB ("APPLICATION_LIST_ENTRY_WORDING") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
