  CREATE TABLE "LIBRA"."COMMUNICATION_MEDIA"
   (    "COMM_ID" NUMBER(10,0) NOT NULL ENABLE,
        "DETAIL" VARCHAR2(254 CHAR) NOT NULL ENABLE,
        "START_DATE" DATE NOT NULL ENABLE,
        "END_DATE" DATE,
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
         CONSTRAINT "COMM_PK" PRIMARY KEY ("COMM_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
