  CREATE TABLE "APPREGISTER"."CRIMINAL_JUSTICE_AREA"
   (    "CJA_ID" NUMBER NOT NULL ENABLE,
        "CJA_CODE" VARCHAR2(2 CHAR) NOT NULL ENABLE,
        "CJA_DESCRIPTION" VARCHAR2(35 CHAR) NOT NULL ENABLE,
         CONSTRAINT "CRIMINAL_JUSTICE_AREA_PK" PRIMARY KEY ("CJA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
