  CREATE TABLE "APPREGISTER"."FEE"
   (    "FEE_ID" NUMBER NOT NULL ENABLE,
        "FEE_REFERENCE" VARCHAR2(12 CHAR) NOT NULL ENABLE,
        "FEE_DESCRIPTION" VARCHAR2(250 CHAR) NOT NULL ENABLE,
        "FEE_VALUE" NUMBER(9,2) NOT NULL ENABLE,
        "FEE_START_DATE" DATE NOT NULL ENABLE,
        "FEE_END_DATE" DATE,
        "FEE_VERSION" NUMBER NOT NULL ENABLE,
        "FEE_CHANGED_BY" NUMBER NOT NULL ENABLE,
        "FEE_CHANGED_DATE" DATE NOT NULL ENABLE,
        "FEE_USER_NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE,
         CONSTRAINT "FEE_ID_PK" PRIMARY KEY ("FEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
