  CREATE TABLE "LIBRA"."LINK_COMMUNICATION_MEDIA"
   (    "LCM_ID" NUMBER(10,0) NOT NULL ENABLE,
        "LCM_TYPE" VARCHAR2(2 CHAR) NOT NULL ENABLE,
        "START_DATE" DATE,
        "END_DATE" DATE,
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "COMM_COMM_ID" NUMBER(10,0) NOT NULL ENABLE,
        "LOC_LOC_ID" NUMBER(10,0),
        "ER_ER_ID" NUMBER(10,0),
        "BU_BU_ID" NUMBER(10,0),
         CONSTRAINT "LCM_PK" PRIMARY KEY ("LCM_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE,
         CONSTRAINT "LCM_ARC" CHECK (decode(BU_BU_ID,null,0,1)+decode(ER_ER_ID,null,0,1)+decode(LOC_LOC_ID,null,0,1) = 1) ENABLE,
         CONSTRAINT "LCM_BU_FK" FOREIGN KEY ("BU_BU_ID")
          REFERENCES "LIBRA"."BUSINESS_UNITS" ("BU_ID") ENABLE,
         CONSTRAINT "LCM_COMM_FK" FOREIGN KEY ("COMM_COMM_ID")
          REFERENCES "LIBRA"."COMMUNICATION_MEDIA" ("COMM_ID") ENABLE,
         CONSTRAINT "LCM_ER_FK" FOREIGN KEY ("ER_ER_ID")
          REFERENCES "LIBRA"."ENTITY_ROLES" ("ER_ID") ENABLE,
         CONSTRAINT "LCM_LOC_FK" FOREIGN KEY ("LOC_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
