  CREATE TABLE "LIBRA"."LINK_ADDRESSES"
   (    "LA_ID" NUMBER(10,0) NOT NULL ENABLE,
        "NO_FIXED_ABODE" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
        "LA_TYPE" VARCHAR2(5 CHAR) NOT NULL ENABLE,
        "START_DATE" DATE NOT NULL ENABLE,
        "END_DATE" DATE,
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "ADR_ADR_ID" NUMBER(10,0) NOT NULL ENABLE,
        "BU_BU_ID" NUMBER(10,0),
        "ER_ER_ID" NUMBER(10,0),
        "LOC_LOC_ID" NUMBER(10,0),
        "HEAD_OFFICE_INDICATOR" VARCHAR2(1 CHAR),
         CONSTRAINT "LA_PK" PRIMARY KEY ("LA_ID")
  USING INDEX REVERSE PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE,
         CONSTRAINT "LA_DATE_RANGE_CHK" CHECK (
/* start_date not null and end date >= start date or null
 and both are dates with 00:00 time */
start_date = TRUNC(start_date) AND
( end_date IS NULL OR
( end_date = TRUNC(end_date)
AND end_date >= start_date
)
)) ENABLE,
         CONSTRAINT "LA_ARC" CHECK (decode(BU_BU_ID,null,0,1)+decode(ER_ER_ID,null,0,1)+decode(LOC_LOC_ID,null,0,1) = 1) DEFERRABLE INITIALLY DEFERRED ENABLE,
         SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
         SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
         SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS,
         SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS,
         CONSTRAINT "LA_ADR_FK" FOREIGN KEY ("ADR_ADR_ID")
          REFERENCES "LIBRA"."ADDRESSES" ("ADR_ID") ENABLE,
         CONSTRAINT "LA_BU_FK" FOREIGN KEY ("BU_BU_ID")
          REFERENCES "LIBRA"."BUSINESS_UNITS" ("BU_ID") ENABLE,
         CONSTRAINT "LA_LOC_FK" FOREIGN KEY ("LOC_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "LA_ER_FK" FOREIGN KEY ("ER_ER_ID")
          REFERENCES "LIBRA"."ENTITY_ROLES" ("ER_ID") DEFERRABLE INITIALLY DEFERRED ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
