  CREATE TABLE "LIBRA"."NATIONAL_COURT_HOUSES"
   (    "NCH_ID" NUMBER(10,0) NOT NULL ENABLE,
        "COURTHOUSE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "COURT_TYPE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
        "START_DATE" DATE NOT NULL ENABLE,
        "END_DATE" DATE,
        "LOC_LOC_ID" NUMBER(10,0),
        "PSA_PSA_ID" NUMBER(10,0),
        "COURT_LOCATION_CODE" VARCHAR2(10 CHAR),
        "SL_COURTHOUSE_NAME" VARCHAR2(100 CHAR),
        "NORG_ID" NUMBER(10,0),
         CONSTRAINT "NCH_PK" PRIMARY KEY ("NCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE,
         CONSTRAINT "NCH_LOC_FK" FOREIGN KEY ("LOC_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "NCH_PSA_FK" FOREIGN KEY ("PSA_PSA_ID")
          REFERENCES "LIBRA"."PETTY_SESSIONAL_AREAS" ("PSA_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
