  CREATE TABLE "LIBRA"."PETTY_SESSIONAL_AREAS"
   (    "PSA_ID" NUMBER(10,0) NOT NULL ENABLE,
        "PSA_NAME" VARCHAR2(100 CHAR),
        "SHORT_NAME" VARCHAR2(10 CHAR),
        "VERSION_NUMBER" NUMBER(38,0) NOT NULL ENABLE,
        "CHANGED_BY" NUMBER(10,0) NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "CMA_CMA_ID" NUMBER(10,0),
        "PSA_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE,
        "START_DATE" DATE,
        "END_DATE" DATE,
        "JC_NAME" VARCHAR2(200 CHAR) DEFAULT 'No name entered',
        "COURT_TYPE" VARCHAR2(10 CHAR) DEFAULT 'PSA' NOT NULL ENABLE,
        "CRIME_CASES_LOC_ID" NUMBER(10,0),
        "FINE_ACCOUNTS_LOC_ID" NUMBER(10,0),
        "MAINTENANCE_ENFORCEMENT_LOC_ID" NUMBER(10,0),
        "FAMILY_CASES_LOC_ID" NUMBER(10,0),
        "COURT_LOCATION_CODE" VARCHAR2(10 CHAR),
        "CENTRAL_FINANCE_LOC_ID" NUMBER(10,0),
        "SL_PSA_NAME" VARCHAR2(100 CHAR),
        "NORG_ID" NUMBER(10,0),
         CONSTRAINT "PSA_PK" PRIMARY KEY ("PSA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"  ENABLE,
         CONSTRAINT "CHK_PSA_CODE" CHECK ((to_number(psa_code) > 0) and (length(psa_code)=4)) ENABLE,
         CONSTRAINT "CHK_JC_NAME" CHECK ( (court_type IN ('PSA', 'YCT') AND jc_name IS NOT NULL) OR (court_type NOT IN ('PSA', 'YCT') )  ) ENABLE,
         SUPPLEMENTAL LOG DATA (ALL) COLUMNS,
         SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS,
         SUPPLEMENTAL LOG DATA (UNIQUE INDEX) COLUMNS,
         SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS,
         CONSTRAINT "PSA_CMA_FK" FOREIGN KEY ("CMA_CMA_ID")
          REFERENCES "LIBRA"."COMMISSION_AREAS" ("CMA_ID") ENABLE,
         CONSTRAINT "PSA_CRIME_CASES_LOC_FK" FOREIGN KEY ("CRIME_CASES_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "PSA_FAMILY_CASES_LOC_FK" FOREIGN KEY ("FAMILY_CASES_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "PSA_FINE_ACCOUNTS_FK" FOREIGN KEY ("FINE_ACCOUNTS_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "PSA_MAINT_ENF_LOC_FK" FOREIGN KEY ("MAINTENANCE_ENFORCEMENT_LOC_ID
")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE,
         CONSTRAINT "PSA_CFU_LOC_FK" FOREIGN KEY ("CENTRAL_FINANCE_LOC_ID")
          REFERENCES "LIBRA"."LOCATIONS" ("LOC_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LIBRA_DATA"
