  CREATE TABLE "APPREGISTER"."RESOLUTION_CODES"
   (    "RC_ID" NUMBER NOT NULL ENABLE,
        "RESOLUTION_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
        "RESOLUTION_CODE_TITLE" VARCHAR2(500 CHAR) NOT NULL ENABLE,
        "RESOLUTION_CODE_WORDING" CLOB NOT NULL ENABLE,
        "RESOLUTION_LEGISLATION" CLOB,
        "RC_DESTINATION_EMAIL_ADDRESS_1" VARCHAR2(253 CHAR),
        "RC_DESTINATION_EMAIL_ADDRESS_2" VARCHAR2(253 CHAR),
        "RESOLUTION_CODE_START_DATE" DATE NOT NULL ENABLE,
        "RESOLUTION_CODE_END_DATE" DATE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
         CONSTRAINT "RESOLUTION_CODES_PK" PRIMARY KEY ("RC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
 LOB ("RESOLUTION_CODE_WORDING") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
 LOB ("RESOLUTION_LEGISLATION") STORE AS (
  TABLESPACE "APPREGISTER_DATA_LOB" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT))
