  CREATE TABLE "APPREGISTER"."STANDARD_APPLICANTS"
   (    "SA_ID" NUMBER NOT NULL ENABLE,
        "STANDARD_APPLICANT_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
        "STANDARD_APPLICANT_START_DATE" DATE NOT NULL ENABLE,
        "STANDARD_APPLICANT_END_DATE" DATE,
        "VERSION" NUMBER NOT NULL ENABLE,
        "CHANGED_BY" NUMBER NOT NULL ENABLE,
        "CHANGED_DATE" DATE NOT NULL ENABLE,
        "USER_NAME" VARCHAR2(250 CHAR),
        "NAME" VARCHAR2(100 CHAR),
        "TITLE" VARCHAR2(100 CHAR),
        "FORENAME_1" VARCHAR2(100 CHAR),
        "FORENAME_2" VARCHAR2(100 CHAR),
        "FORENAME_3" VARCHAR2(100 CHAR),
        "SURNAME" VARCHAR2(100 CHAR),
        "ADDRESS_L1" VARCHAR2(35 CHAR) NOT NULL ENABLE,
        "ADDRESS_L2" VARCHAR2(35 CHAR),
        "ADDRESS_L3" VARCHAR2(35 CHAR),
        "ADDRESS_L4" VARCHAR2(35 CHAR),
        "ADDRESS_L5" VARCHAR2(35 CHAR),
        "POSTCODE" VARCHAR2(8 CHAR),
        "EMAIL_ADDRESS" VARCHAR2(253 CHAR),
        "TELEPHONE_NUMBER" VARCHAR2(20 CHAR),
        "MOBILE_NUMBER" VARCHAR2(20 CHAR),
         CONSTRAINT "STANDARD_APPLICANT_PK" PRIMARY KEY ("SA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "APPREGISTER_DATA"
