"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"<create_import_schema.sql

"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.application_codes_temp FROM 'appregister.application_codes.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.application_lists_temp FROM 'appregister.application_lists.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.application_list_entries_temp FROM 'appregister.application_list_entries.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"

"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.application_register_temp FROM 'appregister.application_register.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.app_list_entry_fee_id_temp FROM 'appregister.app_list_entry_fee_id.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.app_list_entry_fee_status_temp FROM 'appregister.app_list_entry_fee_status.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.app_list_entry_official_temp FROM 'appregister.app_list_entry_official.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.app_list_entry_resolutions_temp FROM 'appregister.app_list_entry_resolutions.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.criminal_justice_area_temp FROM 'appregister.criminal_justice_area.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.fee_temp FROM 'appregister.fee.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.name_address_temp FROM 'appregister.name_address.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"

"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.resolution_codes_temp FROM 'appregister.resolution_codes.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.standard_applicants_temp FROM 'appregister.standard_applicants.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.national_court_houses_temp FROM 'libra.national_court_houses.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.link_addresses_temp FROM 'libra.link_addresses.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.addresses_temp FROM 'libra.addresses.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.link_communication_media_temp FROM 'libra.link_communication_media.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.communication_media_temp FROM 'libra.communication_media.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"
"c:\Program Files\PostgreSQL\16\bin\psql.exe" --set=ON_ERROR_STOP=1 -c "\copy appreg.petty_sessional_areas_temp FROM 'libra.petty_sessional_areas.csv' WITH (FORMAT text, DELIMITER '|', NULL '')" "postgresql://hmcts:<pwd>@appreg-dev.postgres.database.azure.com:5432/appreg-db"


