-- Initial Creation script for table in Oracle required for user mapping

-- Version Control
-- V1.0  	Matthew Harman  17/03/2026	Initial Version

DECLARE
    v_exist NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_exist FROM USER_TABLES WHERE TABLE_NAME = 'APPREG_USER_MAPPING';
    IF v_exist = 1 THEN 
        EXECUTE IMMEDIATE 'DROP TABLE APPREG_USER_MAPPING';
    END IF;
END;
/

CREATE TABLE APPREGISTER.APPREG_USER_MAPPING(
    LEGACY_CHANGED_BY   NUMBER NOT NULL,
    MODERN_CHANGED_BY   VARCHAR2(73) NOT NULL
    );

CREATE INDEX APPREGISTER.APPREG_USER_MAPPING_IDX ON APPREGISTER.APPREG_USER_MAPPING(LEGACY_CHANGED_BY);

CREATE OR REPLACE FUNCTION APPREGISTER.APPREG_GET_USER_MAPPING(legacy APPREG_USER_MAPPING.LEGACY_CHANGED_BY%TYPE)
    RETURN APPREG_USER_MAPPING.MODERN_CHANGED_BY%TYPE
    IS 
        modern APPREG_USER_MAPPING.MODERN_CHANGED_BY%TYPE;
    BEGIN   
        SELECT MODERN_CHANGED_BY INTO modern
            FROM APPREG_USER_MAPPING
            WHERE LEGACY_CHANGED_BY = legacy;
        RETURN modern;
    EXCEPTION   
        WHEN NO_DATA_FOUND THEN 
            -- no mapping found, return default value
            RETURN 'MISSINGM-MISS-MISS-MISS-MISSINGMISSI:72f988bf-86f1-41af-91ab-2d7cd011db47';
        WHEN OTHERS THEN    
            -- can't determine the mapping, return default value
            RETURN 'MISSINGM-MISS-MISS-MISS-MISSINGMISSI:72f988bf-86f1-41af-91ab-2d7cd011db47';
    END;
/

