type: object
description: Request payload to create an Application List.
required:
  - date
  - time
  - description
  - status
  - courtLocation
  - otherLocationDescription
  - criminalJusticeArea

properties:

  date:
    type: string
    format: date

  time:
    type: string
    format: time

  description:
    type: string

  status:
    $ref: './application-list-status.yaml'

  courtLocation:
    allOf:
      - $ref: '../court-locations/court-location-get-detail-dto.yaml'
    nullable: true

  otherLocationDescription:
    type: string
    description: Free-text location if not using a standard court.
    example: "Temporary Courtroom at Town Hall"
    nullable: true

  criminalJusticeArea:
    allOf:
      - $ref: '../criminal-justice-areas/criminal-justice-area-get-dto.yaml'
    nullable: true

  durationHours:
    type: integer
    format: int32
    minimum: 0

  durationMinutes:
    type: integer
    format: int32
    minimum: 0
    maximum: 59
